name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Or use: ubuntu-latest if not using self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/abhishekkkk-15/kubernetes-cicd-tutorial:latest
            ghcr.io/abhishekkkk-15/kubernetes-cicd-tutorial:${{ github.sha }}
      - name: Update GitOps repository
        shell: powershell
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          git config --global credential.helper store
          Set-Content -Path "$env:USERPROFILE\.git-credentials" -Value "https://${env:GIT_TOKEN}:x-oauth-basic@github.com"

          Remove-Item -Recurse -Force gitops -ErrorAction SilentlyContinue
          git clone https://github.com/abhishekkkk-15/grade-api-gitops.git gitops
          Set-Location gitops

          $file = Get-Content deployment.yaml
          $updated = $file -replace 'image: ghcr.io/.*', 'image: ghcr.io/abhishekkkk-15/kubernetes-cicd-tutorial:${{ github.sha }}'
          $updated | Set-Content deployment.yaml

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push -f https://${env:GIT_TOKEN}@github.com/abhishekkkk-15/grade-api-gitops.git main

