name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Debug GitOps authentication
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Print first few characters of token to verify it's set (safe to show just a hint)
          echo "Token starts with: ${GIT_TOKEN:0:4}..."
          
          # Try cloning with basic command
          git clone https://${GIT_TOKEN}@github.com/rslim087a/grade-api-gitops.git gitops
          
          # Create a test file
          cd gitops
          echo "Test from GitHub Actions" > test-actions.txt
          
          # Commit and push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add test-actions.txt
          git commit -m "Test authentication from GitHub Actions"
          git push

      - name: Update GitOps repository
        shell: bash
        run: |
          # Clone the GitOps repository with authentication
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/rslim087a/grade-api-gitops.git gitops
          cd gitops
          
          # Detect macOS and use appropriate sed command
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS version
            sed -i '' "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          else
            # Linux and Git Bash on Windows version
            sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          fi
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
